name: Release FMOD Importer

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    # === SOLUTION ===
    # Grant the job permission to write to the repository's contents,
    # which is required for creating releases and uploading assets.
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version info
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Update version in bl_info (optional)
        run: |
          VERSION_NUM="${{ steps.get_version.outputs.VERSION_NUMBER }}"
          BLENDER_VERSION_TUPLE="${VERSION_NUM//./, }"
          sed -i "s/\"version\": (.*),/\"version\": ($BLENDER_VERSION_TUPLE),/" src/__init__.py

      - name: Create release archive and get info
        id: archive
        run: |
          zip -r fmod_importer_${{ steps.get_version.outputs.VERSION }}.zip ./src -q
          cp fmod_importer_${{ steps.get_version.outputs.VERSION }}.zip fmod_importer.zip
          ls -la *.zip
          FILE_SIZE=$(stat -c%s fmod_importer.zip | numfmt --to=iec-i)
          echo "FILE_SIZE=$FILE_SIZE" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          CHANGELOG_BODY="No changelog available for this release."
          if [ -f CHANGELOG.md ]; then
            CHANGELOG_BODY=$(awk '/^## \[${{ steps.get_version.outputs.VERSION }}\]/{flag=1; next} /^## \[/{flag=0} flag' CHANGELOG.md)
          fi
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: FMOD Importer ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## FMOD Importer ${{ steps.get_version.outputs.VERSION }}

            Blender plugin for importing FMOD model files (.fmod) from Monster Hunter Frontier Z.

            ### Installation
            1. Download the `fmod_importer.zip` file below
            2. In Blender, go to Edit > Preferences > Add-ons
            3. Click "Install..." and select the downloaded zip file
            4. Enable the "FMOD Importer" addon

            ### Changes in this version
            ${{ steps.changelog.outputs.BODY }}

            ---

            **Blender Compatibility**: 3.0+
            **File Size**: ${{ steps.archive.outputs.FILE_SIZE }}B
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, 'alpha') || contains(steps.get_version.outputs.VERSION, 'beta') || contains(steps.get_version.outputs.VERSION, 'rc') }}

      - name: Upload Release Asset (versioned)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fmod_importer_${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: fmod_importer_${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip

      - name: Upload Release Asset (generic name)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fmod_importer.zip
          asset_name: fmod_importer.zip
          asset_content_type: application/zip
